---
title: "Functions"
author: "Matthew Hamilton"
date: "30/11/2021"
output: html_document
---

```{r}
# Function that fit LCA for n clusters
fit_mixture_mdl<-function(ds_tb,
                          clusters_1L_int,
                          var_nms_chr){
     model_def <- depmixS4::mix(purrr::map(var_nms_chr,
                                           ~ eval(parse(text = paste0(.x," ~ 1")))),
                           family = rep(list(depmixS4::multinomial("identity")), length(var_nms_chr)),
                           data = ds_tb,
                           nstates = clusters_1L_int, 
                           nstart = rep(1/clusters_1L_int,clusters_1L_int))
     model_mdl <- depmixS4::fit(model_def)
     return(model_mdl)
}
# Function that return fitting index and results for a data set for 2-15clusters
fit_mixture_mdl_clusters <- function(ds_tb,
                                     nbr_clss_1L_int = 15L,
                                     var_nms_chr){
    return_df <- data.frame(
        Classes = integer(),
        AIC = double(),
        BIC = double(), 
        logLik = double(),
        Par = double())
    return_ds_tb <- ds_tb %>% dplyr::select(ID)
    for(n in 2:nbr_clss_1L_int){
        model_mdl <- fit_mixture_mdl(ds_tb,
                           classes_1L_int = n,
                           var_nms_chr = var_nms_chr)
        return_df <- rbind(return_df,
                           data.frame(Classes = n,
                                      AIC = stats:AIC(model_mdl),
                                      BIC = stats::BIC(model_mdl),
                                      logLik = stats::logLik(model_mdl),
                                      Par = model_mdl@npars))
        return_ds_tb[[paste0("n",n)]] <- apply(model_mdl@posterior %>%
                                                 dplyr::select(-state),
                                               1,
                                               which.max)
    }
    mdl_smry_ls <- list(return_df,return_ds_tb)
    return(mdl_smry_ls)
}
# 10 fold CV
make_cvdn_ls <- function(ds_tb,
                          folds_int,
                          nbr_cores_1L_int = 1L,
                          nbr_clss_1L_int = 15L,
                          var_nms_chr){
    cvdn_ls <- parallel::mclapply(1:max(folds_int), function(i) {
        print(i)
        training_set <- ds_tb[nbr_of_folds_1L_int != i,]
        train_return<-fit_mixture_mdl_clusters(training_set,
                                       nbr_clss_1L_int = nbr_clss_1L_int,
                                       var_nms_chr = var_nms_chr) 
    }, mc.cores = nbr_cores_1L_int) 
    return(cvdn_ls )
}
# function extract legend of figure 
# function plot sum domain scores
plot_cluster<- function(ds_tb,
                        cluster_int){
    #extract column name 
    colNames <- names(ds_tb)[21:26]
    ds_tb$cluster_int <- cluster_int
    
    plot_ls<-list()
    # loop summary measures 
    for(i in colNames){ 
      labelx <- eval(parse(text=paste0("attributes(ds_tb$",i,")$label")))
      labelx <- stringr::str_to_sentence(stringr::str_sub(labelx,38,55))
      plot_ls[[i]]<- ggplot2::ggplot(ds_tb, ggplot2::aes_string(i)) +
        ggplot2::geom_density(ggplot2::aes(fill = cluster_int,
                                           colour = cluster_int), 
                              alpha = 0.4 ,
                              adjust = 2.5) +
        ggplot2::labs(x=labelx,y="Density") + 
        ggplot2::theme_bw() + 
        ggplot2::theme(legend.position="none") +
        ggplot2::scale_fill_manual(values  = c("#fdcc8a","#fc8d59","#e34a33", "#b30000")) +
        ggplot2::scale_colour_manual(values  = c("#fdcc8a","#fc8d59","#e34a33", "#b30000")) 
    }          
    #save legend from one plot 
   legend <- ggplot2::ggplot(ds_tb, ggplot2::aes_string(i)) +
     ggplot2::geom_density(ggplot2::aes(fill = cluster_int, 
                                        colour = cluster_int), 
                           alpha=0.4,
                           adjust=2.5) +
     ggplot2::labs(x=labelx,
                   y="Density",
                   fill="Class",
                   col="Class")  + 
     ggplot2::theme_bw() + 
     ggplot2::theme(legend.position="bottom") +
     ggplot2::scale_fill_manual(values  = c("#fdcc8a","#fc8d59","#e34a33", "#b30000")) +
     ggplot2::scale_colour_manual(values  = c("#fdcc8a","#fc8d59","#e34a33", "#b30000")) 
   legend <- youthvars::get_guide_box_lgd(legend)
   #arrange all plot together
   print(gridExtra::grid.arrange(ggpubr::ggarrange(plotlist = plot_ls,
                                                   nrow = 3, 
                                                   ncol = 2) ,
             legend, 
             nrow = 2,
             heights=c(10, 1)))
}
```

```{r}
add_class_var <- function(ds_tb,
                          clusters_1L_int,
                          model_mdl,
                          class_var_nm_1L_chr = "class_int"){
  ds_tb <- ds_tb %>%
    dplyr::mutate(!!rlang::sym(class_var_nm_1L_chr) := as.factor(apply(model_mdl@posterior[,2:(clusters_1L_int + 1)],
                                                                       1,
                                                                       which.max)))
  return(ds_tb)
}
add_kmeans_cls_var <- function(ds_tb,
                               classes_1L_int,
                               components_1L_int,
                               pca_df,
                               kmeans_var_nm_1L_chr = "kmeans_cls_int",
                               start_1L_int = 25L){
  kmeans_ls <- kmeans(pca_df[,1:components_1L_int],
                      centers = classes_1L_int, 
                      nstart = start_1L_int)
  ds_tb <- ds_tb %>%
    dplyr::mutate(!!rlang::sym(kmeans_var_nm_1L_chr) := as.factor(kmeans_ls$cluster))
  return(ds_tb)
}
calculate_mean_RI <- function(cv_results_ls,
                              ds_tb,
                              fold_id_nm_1L_chr = "Fold",
                              id_var_nm_1L_chr = "ID",
                              select_from_ls_1L_int = 2L,
                              select_from_df_int = c(1L,4L)){
  cv_ds_ls <- make_cv_ds(cv_results_ls,
                         fold_id_nm_1L_chr = fold_id_nm_1L_chr,
                         select_from_ls_1L_int = select_from_ls_1L_int,
                         select_from_df_int = select_from_df_int)
Rand_idx_mat <- make_Rand_idx_mat(cv_ds_ls,
                                  ds_tb = ds_tb,
                                  id_var_nm_1L_chr = id_var_nm_1L_chr)
mean_RI_dbl <- mean(Rand_idx_mat,na.rm = TRUE)
return(mean_RI_dbl)
}
calculate_sngl_Rand_idx <- function(i,j,data_tb){
  Rand_idx_dbl <- 1
  if(i!=j){
    data_tb <- data_tb[,c(i,j)] %>% na.omit()
    Rand_idx_dbl <- aricode::RI(data_tb %>% dplyr::pull(1), # EDITED
                          data_tb %>% dplyr::pull(2)) # EDITED
  }
  return(Rand_idx_dbl)
}

get_nbr_of_clss <- function(cv_ds_tb,
                            clss_var_nm_1L_chr = "Classes"){
    nbr_of_clss_1L_dbl <- cv_ds_tb %>%
    dplyr::pull(!!rlang::sym(clss_var_nm_1L_chr)) %>% #
    unique() %>% 
    length() + 1
    return(nbr_of_clss_1L_dbl)
}
make_cv_ds <- function(cv_results_ls,
                       select_from_ls_1L_int = 1L,
                       select_from_df_int = NA_integer_,
                       fold_id_nm_1L_chr = "Fold"){
# cv_results<-lapply(cv_results_ls, `[[`, 2)
# cv_results<-lapply(cv_results, `[`, c(1,4))
 tfd_cv_results_ls <- lapply(cv_results_ls, `[[`, select_from_ls_1L_int)
 if(!is.na(select_from_df_int[1])){
   cv_ds_xx <- lapply(tfd_cv_results_ls, `[`, select_from_df_int)
 }else{
    cv_ds_xx <- data.table::rbindlist(tfd_cv_results_ls, 
                                   idcol = fold_id_nm_1L_chr) 
 }
return(cv_ds_xx)
}
make_cv_points_ds <- function(smry_cv_ds_tb,
                              statistic_var_nm_1L_chr,
                              clss_var_nm_1L_chr = "Classes",
                              maximise_1L_lgl = F){
  if(maximise_1L_lgl){
    fns_ls <- list(fn1 = which.max,
                   fn2 = max)
  }else{
    fns_ls <- list(fn1 = which.min,
                   fn2 = min)
  }
  cv_points_ds_df <- data.frame(var_one = smry_cv_ds_tb[rlang::exec(fns_ls$fn1,smry_cv_ds_tb %>% dplyr::pull(!!rlang::sym(statistic_var_nm_1L_chr))),#DIFF
                                                        clss_var_nm_1L_chr], 
                                var_two = rlang::exec(fns_ls$fn2,smry_cv_ds_tb %>%
                                            dplyr::pull(!!rlang::sym(statistic_var_nm_1L_chr))))
  names(cv_points_ds_df) <- c(clss_var_nm_1L_chr,statistic_var_nm_1L_chr)#DIFF
  return(cv_points_ds_df)
}
make_average_fit_plt <- function(cv_ds_tb,
                        nbr_of_clss_1L_dbl,
                        statistic_var_nm_1L_chr,
                        clss_var_nm_1L_chr = "Classes",
                        maximise_1L_lgl = F,
                        y_label_1L_chr = NA_character_){
    smry_cv_ds_tb <- make_smry_cv_ds(cv_ds_tb,
                                 clss_var_nm_1L_chr = clss_var_nm_1L_chr,
                                 statistic_var_nm_1L_chr = statistic_var_nm_1L_chr) 
    cv_points_ds_df <- make_cv_points_ds(smry_cv_ds_tb,
                                         maximise_1L_lgl = maximise_1L_lgl,
                                         statistic_var_nm_1L_chr = statistic_var_nm_1L_chr)
    plt <- ggplot2::ggplot(smry_cv_ds_tb) +
  ggplot2::geom_line(ggplot2::aes(x = !!rlang::sym(clss_var_nm_1L_chr),#
                                  y = !!rlang::sym(statistic_var_nm_1L_chr)) ) + #DIFF
  ggplot2::theme_bw() + 
  ggplot2::theme(legend.position="none") 
  if(!is.na(y_label_1L_chr)){
    plt <- plt   + 
  ggplot2::labs(y=y_label_1L_chr)  #DIFF [EXTRA]
  }
  plt <- plt +
  ggplot2::scale_x_continuous(breaks = 2:nbr_of_clss_1L_dbl,
                              limits = c(2, nbr_of_clss_1L_dbl)) +
  ggplot2::geom_point(ggplot2::aes(x = cv_points_ds_df %>% dplyr::pull(!!rlang::sym(clss_var_nm_1L_chr)), #DIFF
                                   y = cv_points_ds_df %>% dplyr::pull(!!rlang::sym(statistic_var_nm_1L_chr))), #DIFF
                      color = "red",
                      size=3) 
  return(plt)
}
make_individual_fit_plt <- function(tfd_cv_ds_tb,
                                    nbr_of_clss_1L_dbl,
                                    statistic_var_nm_1L_chr,
                                    clss_var_nm_1L_chr = "Classes",
                                    fold_var_nm_1L_chr = "Fold",
                                    maximise_1L_lgl = F,
                                    y_label_1L_chr = NA_character_){
  smry_var_nms_chr <- make_smry_var_nms(statistic_var_nm_1L_chr,
                                   maximise_1L_lgl = maximise_1L_lgl)
      plt <- ggplot2::ggplot(tfd_cv_ds_tb,
                        ggplot2::aes(x = !!rlang::sym(clss_var_nm_1L_chr),#
                                        y = !!rlang::sym(statistic_var_nm_1L_chr),#DIFF 
                                        color = factor(!!rlang::sym(fold_var_nm_1L_chr))))
  if(!is.na(y_label_1L_chr)){
    plt <- plt   + 
  ggplot2::labs(y = y_label_1L_chr)  #DIFF [EXTRA]
  }
    plt <- plt +
      ggplot2::geom_line() + 
      ggplot2::theme_bw() +
      ggplot2::theme(legend.position="none") +
      ggplot2::scale_x_continuous(breaks = 2:nbr_of_clss_1L_dbl,
                                  limits = c(2, nbr_of_clss_1L_dbl)) +
      ggplot2::geom_point(ggplot2::aes(x = !!rlang::sym(smry_var_nms_chr[2]), # DIFF 
                                       y = !!rlang::sym(smry_var_nms_chr[1])), # DIFF 
                      size=2) 
  return(plt)
}
make_Rand_idx_mat <- function(cv_ds_ls,
                              ds_tb,
                              id_var_nm_1L_chr = "ID"){
  RI_calcn_ds_tb <- make_ds_for_RI_calc(cv_ds_ls = cv_ds_ls,
                                   ds_tb = ds_tb,
                                   id_var_nm_1L_chr = id_var_nm_1L_chr)
  nbr_of_folds_1L_int <- ncol(RI_calcn_ds_tb)
  cal_RI <- Vectorize(calculate_sngl_Rand_idx, 
                      vectorize.args = list("i","j"))
  Rand_idx_mat <- outer(1:nbr_of_folds_1L_int,
                        1:nbr_of_folds_1L_int,
                        cal_RI,
                        data_tb = RI_calcn_ds_tb)
  diag(Rand_idx_mat) <- NA
return(Rand_idx_mat)
}
make_ds_for_RI_calc <- function(cv_ds_ls,
                                ds_tb,
                                id_var_nm_1L_chr = "ID"){
  tfd_ds_tb <- ds_tb  %>% 
  dplyr::select(!!rlang::sym(id_var_nm_1L_chr))
for(i in 1:length(cv_ds_ls)){
  tfd_ds_tb <- tfd_ds_tb %>% 
    dplyr::left_join(cv_ds_ls[[i]],
                     by = id_var_nm_1L_chr)
  names(tfd_ds_tb)[i+1] <- paste("fold",i) 
}
tfd_ds_tb <- tfd_ds_tb %>% 
  dplyr::select(-!!rlang::sym(id_var_nm_1L_chr)) %>% 
  dplyr::mutate_all(as.factor)
return(tfd_ds_tb)
}
make_pca_tbl <- function(ds_tb,
                         var_nms_chr,
                         class_var_nm_1L_chr = "class_int"){
  pca_ls <- stats::prcomp(ds_tb %>%
                          dplyr::select(tidyselect::all_of(var_nms_chr)) %>% 
              dplyr::mutate_all(as.numeric),
              scale.=T)
    pca_df <- as.data.frame(pca_ls$x) %>%
    dplyr::mutate(!!rlang::sym(class_var_nm_1L_chr) := as.factor(ds_tb %>% 
                                dplyr::pull(!!rlang::sym(class_var_nm_1L_chr))))
  return(pca_df)
}
make_smry_cv_ds <- function(cv_ds_tb,
                            statistic_var_nm_1L_chr,
                            clss_var_nm_1L_chr = "Classes"
                                      ){
  smry_cv_ds_tb <- cv_ds_tb %>% # RENAME
  dplyr::group_by(!!rlang::sym(clss_var_nm_1L_chr)) %>% 
  dplyr::summarise(!!rlang::sym(statistic_var_nm_1L_chr) := mean(!!rlang::sym(statistic_var_nm_1L_chr))) %>% #DIFF
  dplyr::ungroup() 
  return(smry_cv_ds_tb)
}
make_smry_var_nms <- function(statistic_var_nm_1L_chr,
                              maximise_1L_lgl = F){
    smry_var_nms_chr <- paste0(ifelse(maximise_1L_lgl,"max","min"),
                            statistic_var_nm_1L_chr,
                            c("","which"))
    return(smry_var_nms_chr)
}
plot_average_fit <- function(cv_ds_tb,
                             clss_var_nm_1L_chr = "Classes"){
  nbr_of_clss_1L_dbl <- get_nbr_of_clss(cv_ds_tb,
                                        clss_var_nm_1L_chr = clss_var_nm_1L_chr)
  plot_ls <- list()
plot_ls[[1]] <- make_average_fit_plt(cv_ds_tb,
                         nbr_of_clss_1L_dbl = nbr_of_clss_1L_dbl, 
                         statistic_var_nm_1L_chr = "AIC") 
plot_ls[[2]] <- make_average_fit_plt(cv_ds_tb,
                         nbr_of_clss_1L_dbl = nbr_of_clss_1L_dbl, 
                         statistic_var_nm_1L_chr = "BIC")
plot_ls[[3]] <- make_average_fit_plt(cv_ds_tb,
                         maximise_1L_lgl = T,
                         nbr_of_clss_1L_dbl = nbr_of_clss_1L_dbl, 
                         statistic_var_nm_1L_chr = "logLik",
                         y_label_1L_chr = "Log-likelihood")
average_fit_plt <- gridExtra::grid.arrange(ggpubr::ggarrange(plotlist = plot_ls, 
                                          ncol=1))
return(average_fit_plt)
}
print_cluster_plots <- function(ds_tb,
                                clusters_1L_int,
                                var_nms_chr,
                                nbr_of_folds_1L_int = 2L,
                                var_idc_1L_int = 1L){
  folds_int <- caret::createFolds(ds_tb$Q1, 
                                  k = nbr_of_folds_1L_int,
                                  list = FALSE)
for(i in 1:nbr_of_folds_1L_int){
        testing_set <- ds_tb[folds_int == i,]
        model_mdl <- fit_mixture_mdl(testing_set,
                           clusters_1L_int = clusters_1L_int,#4
                           var_nms_chr = var_nms_chr)#paste0("Q",1:20)
        print(plot_cluster(testing_set,
                           cluster_int = as.factor(apply(model_mdl@posterior[,2:(clusters_1L_int + 1)],
                                           1,
                                           which.max))))
 }
}
transform_cv_ds_for_ind_plts <- function(cv_ds_tb,
                                         clss_var_nm_1L_chr = "Classes",
                                         fold_var_nm_1L_chr = "Fold"){
  aic_vars_chr <- make_smry_var_nms("AIC")
  bic_vars_chr <- make_smry_var_nms("BIC")
  logLik_vars_chr <- make_smry_var_nms("logLik",
                                       maximise_1L_lgl = T)
  tfd_cv_ds_tb <- cv_ds_tb %>% 
   dplyr::group_by(!!rlang::sym(fold_var_nm_1L_chr)) %>% 
   dplyr::mutate(!!rlang::sym(aic_vars_chr[1]) := min(AIC),
          !!rlang::sym(bic_vars_chr[1]) := min(BIC),
          !!rlang::sym(logLik_vars_chr[1]) := max(logLik)) %>% 
   dplyr::mutate(!!rlang::sym(aic_vars_chr[2]) := ifelse(!!rlang::sym(aic_vars_chr[1]) == AIC, 
                                                         !!rlang::sym(clss_var_nm_1L_chr), 
                                                         NA),
                 !!rlang::sym(bic_vars_chr[2]) := ifelse(!!rlang::sym(bic_vars_chr[1]) == BIC, 
                                                         !!rlang::sym(clss_var_nm_1L_chr), 
                                                         NA),
                 !!rlang::sym(logLik_vars_chr[2]) := ifelse(!!rlang::sym(logLik_vars_chr[1]) == logLik, 
                                                         !!rlang::sym(clss_var_nm_1L_chr), 
                                                         NA)) %>% 
    dplyr::mutate(!!rlang::sym(aic_vars_chr[2]) := max(!!rlang::sym(aic_vars_chr[2]),na.rm = TRUE),
                  !!rlang::sym(bic_vars_chr[2]) := max(!!rlang::sym(bic_vars_chr[2]),na.rm = TRUE),
                  !!rlang::sym(logLik_vars_chr[2]) := max(!!rlang::sym(logLik_vars_chr[2]),na.rm = TRUE)) %>% 
   dplyr::ungroup()
  return(tfd_cv_ds_tb)
}
plot_individual_fit <- function(cv_ds_tb,
                                clss_var_nm_1L_chr = "Classes",
                                fold_var_nm_1L_chr = "Fold",
                                legend_label_1L_chr = "Datasets"){
  nbr_of_clss_1L_dbl <- get_nbr_of_clss(cv_ds_tb,
                                        clss_var_nm_1L_chr = clss_var_nm_1L_chr)
  tfd_cv_ds_tb <- transform_cv_ds_for_ind_plts(cv_ds_tb,
                               clss_var_nm_1L_chr = clss_var_nm_1L_chr,
                                fold_var_nm_1L_chr = fold_var_nm_1L_chr)
  
    plot_ls <- list()
plot_ls[[1]] <- make_individual_fit_plt(tfd_cv_ds_tb,
                        nbr_of_clss_1L_dbl = nbr_of_clss_1L_dbl,
                        statistic_var_nm_1L_chr = "AIC",
                        clss_var_nm_1L_chr = clss_var_nm_1L_chr,
                        fold_var_nm_1L_chr = fold_var_nm_1L_chr,
                        maximise_1L_lgl = F,
                        y_label_1L_chr = NA_character_)
plot_ls[[2]] <- make_individual_fit_plt(tfd_cv_ds_tb,
                        nbr_of_clss_1L_dbl = nbr_of_clss_1L_dbl,
                        statistic_var_nm_1L_chr = "BIC",
                        clss_var_nm_1L_chr = clss_var_nm_1L_chr,
                        fold_var_nm_1L_chr = fold_var_nm_1L_chr,
                        maximise_1L_lgl = F,
                        y_label_1L_chr = NA_character_) 
plot_ls[[3]] <- make_individual_fit_plt(tfd_cv_ds_tb,
                        nbr_of_clss_1L_dbl = nbr_of_clss_1L_dbl,
                        statistic_var_nm_1L_chr = "logLik",
                        clss_var_nm_1L_chr = clss_var_nm_1L_chr,
                        fold_var_nm_1L_chr = fold_var_nm_1L_chr,
                        maximise_1L_lgl = T,
                        y_label_1L_chr = "Log-likelihood") 
legend <- ggplot2::ggplot(tfd_cv_ds_tb, # USE TTU MTHD
                ggplot2::aes(x = !!rlang::sym(clss_var_nm_1L_chr), 
                             y= AIC, 
                             color=factor(!!rlang::sym(fold_var_nm_1L_chr)))) +
  ggplot2::geom_line() + 
  ggplot2::theme_bw() + 
  ggplot2::theme(legend.position = "bottom") +
  ggplot2::labs(col = legend_label_1L_chr)
legend <- youthvars::get_guide_box_lgd(legend)
individual_fit_plt <- gridExtra::grid.arrange(ggpubr::ggarrange(plotlist = plot_ls,
                                  ncol=1),
                        legend, 
                        nrow = 2, 
                        heights = c(10, 1))
return(individual_fit_plt)
}
plot_pca <- function(ds_tb,
                     pca_df,
                     class_var_nm_1L_chr = "class_int"){
ggplot2::ggplot(pca_df, 
                ggplot2::aes(x = PC1, 
                             y = PC2, 
                             colour = !!rlang::sym(class_var_nm_1L_chr))) + 
  ggplot2::geom_jitter(alpha = 0.3) + 
  ggplot2::theme_bw()
                     }
```
